version: '3.0'
services:
  db:
    image: mysql:latest
    ports:
      - "5432:5432"
    volumes:
      - './docker/db:/var/lib/mysql:rw'
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: pw
      MYSQL_ROOT_PASSWORD: pw
