version: '3.0'
services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "./docker/db/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "postgres_db"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "admin"
